// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module systolic_array_pe_array (
        A_0_address0,
        A_0_ce0,
        A_0_d0,
        A_0_q0,
        A_0_we0,
        A_0_address1,
        A_0_ce1,
        A_0_d1,
        A_0_q1,
        A_0_we1,
        A_1_address0,
        A_1_ce0,
        A_1_d0,
        A_1_q0,
        A_1_we0,
        A_1_address1,
        A_1_ce1,
        A_1_d1,
        A_1_q1,
        A_1_we1,
        A_2_address0,
        A_2_ce0,
        A_2_d0,
        A_2_q0,
        A_2_we0,
        A_2_address1,
        A_2_ce1,
        A_2_d1,
        A_2_q1,
        A_2_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [1:0] A_0_address0;
output   A_0_ce0;
output  [31:0] A_0_d0;
input  [31:0] A_0_q0;
output   A_0_we0;
output  [1:0] A_0_address1;
output   A_0_ce1;
output  [31:0] A_0_d1;
input  [31:0] A_0_q1;
output   A_0_we1;
output  [1:0] A_1_address0;
output   A_1_ce0;
output  [31:0] A_1_d0;
input  [31:0] A_1_q0;
output   A_1_we0;
output  [1:0] A_1_address1;
output   A_1_ce1;
output  [31:0] A_1_d1;
input  [31:0] A_1_q1;
output   A_1_we1;
output  [1:0] A_2_address0;
output   A_2_ce0;
output  [31:0] A_2_d0;
input  [31:0] A_2_q0;
output   A_2_we0;
output  [1:0] A_2_address1;
output   A_2_ce1;
output  [31:0] A_2_d1;
input  [31:0] A_2_q1;
output   A_2_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    load_a13_U0_ap_start;
wire    load_a13_U0_ap_done;
wire    load_a13_U0_ap_continue;
wire    load_a13_U0_ap_idle;
wire    load_a13_U0_ap_ready;
wire    load_a13_U0_start_out;
wire    load_a13_U0_start_write;
wire   [31:0] load_a13_U0_A_nxt_din;
wire    load_a13_U0_A_nxt_write;
wire   [1:0] load_a13_U0_A_0_address0;
wire    load_a13_U0_A_0_ce0;
wire    load_a14_U0_ap_start;
wire    load_a14_U0_ap_done;
wire    load_a14_U0_ap_continue;
wire    load_a14_U0_ap_idle;
wire    load_a14_U0_ap_ready;
wire    load_a14_U0_start_out;
wire    load_a14_U0_start_write;
wire   [31:0] load_a14_U0_A_nxt14_din;
wire    load_a14_U0_A_nxt14_write;
wire   [1:0] load_a14_U0_A_1_address0;
wire    load_a14_U0_A_1_ce0;
wire    load_a15_U0_ap_start;
wire    load_a15_U0_ap_done;
wire    load_a15_U0_ap_continue;
wire    load_a15_U0_ap_idle;
wire    load_a15_U0_ap_ready;
wire    load_a15_U0_start_out;
wire    load_a15_U0_start_write;
wire   [31:0] load_a15_U0_A_nxt28_din;
wire    load_a15_U0_A_nxt28_write;
wire   [1:0] load_a15_U0_A_2_address0;
wire    load_a15_U0_A_2_ce0;
wire    load_b16_U0_ap_start;
wire    load_b16_U0_ap_done;
wire    load_b16_U0_ap_continue;
wire    load_b16_U0_ap_idle;
wire    load_b16_U0_ap_ready;
wire   [31:0] load_b16_U0_B_nxt_din;
wire    load_b16_U0_B_nxt_write;
wire    load_b17_U0_ap_start;
wire    load_b17_U0_ap_done;
wire    load_b17_U0_ap_continue;
wire    load_b17_U0_ap_idle;
wire    load_b17_U0_ap_ready;
wire    load_b17_U0_start_out;
wire    load_b17_U0_start_write;
wire   [31:0] load_b17_U0_B_nxt1_din;
wire    load_b17_U0_B_nxt1_write;
wire    load_b18_U0_ap_start;
wire    load_b18_U0_ap_done;
wire    load_b18_U0_ap_continue;
wire    load_b18_U0_ap_idle;
wire    load_b18_U0_ap_ready;
wire    load_b18_U0_start_out;
wire    load_b18_U0_start_write;
wire   [31:0] load_b18_U0_B_nxt2_din;
wire    load_b18_U0_B_nxt2_write;
wire    PE19_U0_ap_start;
wire    PE19_U0_ap_done;
wire    PE19_U0_ap_continue;
wire    PE19_U0_ap_idle;
wire    PE19_U0_ap_ready;
wire    PE19_U0_A_pre_read;
wire    PE19_U0_B_pre_read;
wire   [31:0] PE19_U0_A_nxt20_din;
wire    PE19_U0_A_nxt20_write;
wire   [31:0] PE19_U0_B_nxt8_din;
wire    PE19_U0_B_nxt8_write;
wire    PE20_U0_ap_start;
wire    PE20_U0_ap_done;
wire    PE20_U0_ap_continue;
wire    PE20_U0_ap_idle;
wire    PE20_U0_ap_ready;
wire    PE20_U0_start_out;
wire    PE20_U0_start_write;
wire    PE20_U0_A_pre1_read;
wire    PE20_U0_B_pre12_read;
wire   [31:0] PE20_U0_A_nxt21_din;
wire    PE20_U0_A_nxt21_write;
wire   [31:0] PE20_U0_B_nxt831_din;
wire    PE20_U0_B_nxt831_write;
wire    PE21_U0_ap_start;
wire    PE21_U0_start_full_n;
wire    PE21_U0_ap_done;
wire    PE21_U0_ap_continue;
wire    PE21_U0_ap_idle;
wire    PE21_U0_ap_ready;
wire    PE21_U0_start_out;
wire    PE21_U0_start_write;
wire    PE21_U0_A_pre2_read;
wire    PE21_U0_B_pre13_read;
wire   [31:0] PE21_U0_A_nxt22_din;
wire    PE21_U0_A_nxt22_write;
wire   [31:0] PE21_U0_B_nxt832_din;
wire    PE21_U0_B_nxt832_write;
wire    PE22_U0_ap_start;
wire    PE22_U0_ap_done;
wire    PE22_U0_ap_continue;
wire    PE22_U0_ap_idle;
wire    PE22_U0_ap_ready;
wire    PE22_U0_A_pre14_read;
wire    PE22_U0_B_pre3_read;
wire   [31:0] PE22_U0_A_nxt623_din;
wire    PE22_U0_A_nxt623_write;
wire   [31:0] PE22_U0_B_nxt9_din;
wire    PE22_U0_B_nxt9_write;
wire    PE23_U0_ap_start;
wire    PE23_U0_ap_done;
wire    PE23_U0_ap_continue;
wire    PE23_U0_ap_idle;
wire    PE23_U0_ap_ready;
wire    PE23_U0_A_pre15_read;
wire    PE23_U0_B_pre314_read;
wire   [31:0] PE23_U0_A_nxt624_din;
wire    PE23_U0_A_nxt624_write;
wire   [31:0] PE23_U0_B_nxt933_din;
wire    PE23_U0_B_nxt933_write;
wire    PE24_U0_ap_start;
wire    PE24_U0_start_full_n;
wire    PE24_U0_ap_done;
wire    PE24_U0_ap_continue;
wire    PE24_U0_ap_idle;
wire    PE24_U0_ap_ready;
wire    PE24_U0_start_out;
wire    PE24_U0_start_write;
wire    PE24_U0_A_pre16_read;
wire    PE24_U0_B_pre315_read;
wire   [31:0] PE24_U0_A_nxt625_din;
wire    PE24_U0_A_nxt625_write;
wire   [31:0] PE24_U0_B_nxt934_din;
wire    PE24_U0_B_nxt934_write;
wire    PE25_U0_ap_start;
wire    PE25_U0_start_full_n;
wire    PE25_U0_ap_done;
wire    PE25_U0_ap_continue;
wire    PE25_U0_ap_idle;
wire    PE25_U0_ap_ready;
wire    PE25_U0_start_out;
wire    PE25_U0_start_write;
wire    PE25_U0_A_pre28_read;
wire    PE25_U0_B_pre4_read;
wire   [31:0] PE25_U0_A_nxt726_din;
wire    PE25_U0_A_nxt726_write;
wire   [31:0] PE25_U0_B_nxt10_din;
wire    PE25_U0_B_nxt10_write;
wire    PE26_U0_ap_start;
wire    PE26_U0_ap_done;
wire    PE26_U0_ap_continue;
wire    PE26_U0_ap_idle;
wire    PE26_U0_ap_ready;
wire    PE26_U0_start_out;
wire    PE26_U0_start_write;
wire    PE26_U0_A_pre29_read;
wire    PE26_U0_B_pre416_read;
wire   [31:0] PE26_U0_A_nxt727_din;
wire    PE26_U0_A_nxt727_write;
wire   [31:0] PE26_U0_B_nxt1035_din;
wire    PE26_U0_B_nxt1035_write;
wire    PE27_U0_ap_start;
wire    PE27_U0_start_full_n;
wire    PE27_U0_ap_done;
wire    PE27_U0_ap_continue;
wire    PE27_U0_ap_idle;
wire    PE27_U0_ap_ready;
wire    PE27_U0_start_out;
wire    PE27_U0_start_write;
wire    PE27_U0_A_pre210_read;
wire    PE27_U0_B_pre417_read;
wire   [31:0] PE27_U0_A_nxt728_din;
wire    PE27_U0_A_nxt728_write;
wire   [31:0] PE27_U0_B_nxt1036_din;
wire    PE27_U0_B_nxt1036_write;
wire    drain_a28_U0_ap_start;
wire    drain_a28_U0_ap_done;
wire    drain_a28_U0_ap_continue;
wire    drain_a28_U0_ap_idle;
wire    drain_a28_U0_ap_ready;
wire    drain_a28_U0_A_pre_V3_read;
wire    ap_sync_continue;
wire    drain_a29_U0_ap_start;
wire    drain_a29_U0_ap_done;
wire    drain_a29_U0_ap_continue;
wire    drain_a29_U0_ap_idle;
wire    drain_a29_U0_ap_ready;
wire    drain_a29_U0_A_pre_V17_read;
wire    drain_a30_U0_ap_start;
wire    drain_a30_U0_ap_done;
wire    drain_a30_U0_ap_continue;
wire    drain_a30_U0_ap_idle;
wire    drain_a30_U0_ap_ready;
wire    drain_a30_U0_A_pre_V211_read;
wire    drain_b31_U0_ap_start;
wire    drain_b31_U0_ap_done;
wire    drain_b31_U0_ap_continue;
wire    drain_b31_U0_ap_idle;
wire    drain_b31_U0_ap_ready;
wire    drain_b31_U0_B_pre_V3_read;
wire    drain_b32_U0_ap_start;
wire    drain_b32_U0_ap_done;
wire    drain_b32_U0_ap_continue;
wire    drain_b32_U0_ap_idle;
wire    drain_b32_U0_ap_ready;
wire    drain_b32_U0_B_pre_V39_read;
wire    drain_b33_U0_ap_start;
wire    drain_b33_U0_ap_done;
wire    drain_b33_U0_ap_continue;
wire    drain_b33_U0_ap_idle;
wire    drain_b33_U0_ap_ready;
wire    drain_b33_U0_B_pre_V310_read;
wire    A_inter_0_0_V_full_n;
wire   [31:0] A_inter_0_0_V_dout;
wire    A_inter_0_0_V_empty_n;
wire    A_inter_1_0_V_full_n;
wire   [31:0] A_inter_1_0_V_dout;
wire    A_inter_1_0_V_empty_n;
wire    A_inter_2_0_V_full_n;
wire   [31:0] A_inter_2_0_V_dout;
wire    A_inter_2_0_V_empty_n;
wire    B_inter_0_0_V_full_n;
wire   [31:0] B_inter_0_0_V_dout;
wire    B_inter_0_0_V_empty_n;
wire    B_inter_0_1_V_full_n;
wire   [31:0] B_inter_0_1_V_dout;
wire    B_inter_0_1_V_empty_n;
wire    B_inter_0_2_V_full_n;
wire   [31:0] B_inter_0_2_V_dout;
wire    B_inter_0_2_V_empty_n;
wire    A_inter_0_1_V_full_n;
wire   [31:0] A_inter_0_1_V_dout;
wire    A_inter_0_1_V_empty_n;
wire    B_inter_1_0_V_full_n;
wire   [31:0] B_inter_1_0_V_dout;
wire    B_inter_1_0_V_empty_n;
wire    A_inter_0_2_V_full_n;
wire   [31:0] A_inter_0_2_V_dout;
wire    A_inter_0_2_V_empty_n;
wire    B_inter_1_1_V_full_n;
wire   [31:0] B_inter_1_1_V_dout;
wire    B_inter_1_1_V_empty_n;
wire    A_inter_0_3_V_full_n;
wire   [31:0] A_inter_0_3_V_dout;
wire    A_inter_0_3_V_empty_n;
wire    B_inter_1_2_V_full_n;
wire   [31:0] B_inter_1_2_V_dout;
wire    B_inter_1_2_V_empty_n;
wire    A_inter_1_1_V_full_n;
wire   [31:0] A_inter_1_1_V_dout;
wire    A_inter_1_1_V_empty_n;
wire    B_inter_2_0_V_full_n;
wire   [31:0] B_inter_2_0_V_dout;
wire    B_inter_2_0_V_empty_n;
wire    A_inter_1_2_V_full_n;
wire   [31:0] A_inter_1_2_V_dout;
wire    A_inter_1_2_V_empty_n;
wire    B_inter_2_1_V_full_n;
wire   [31:0] B_inter_2_1_V_dout;
wire    B_inter_2_1_V_empty_n;
wire    A_inter_1_3_V_full_n;
wire   [31:0] A_inter_1_3_V_dout;
wire    A_inter_1_3_V_empty_n;
wire    B_inter_2_2_V_full_n;
wire   [31:0] B_inter_2_2_V_dout;
wire    B_inter_2_2_V_empty_n;
wire    A_inter_2_1_V_full_n;
wire   [31:0] A_inter_2_1_V_dout;
wire    A_inter_2_1_V_empty_n;
wire    B_inter_3_0_V_full_n;
wire   [31:0] B_inter_3_0_V_dout;
wire    B_inter_3_0_V_empty_n;
wire    A_inter_2_2_V_full_n;
wire   [31:0] A_inter_2_2_V_dout;
wire    A_inter_2_2_V_empty_n;
wire    B_inter_3_1_V_full_n;
wire   [31:0] B_inter_3_1_V_dout;
wire    B_inter_3_1_V_empty_n;
wire    A_inter_2_3_V_full_n;
wire   [31:0] A_inter_2_3_V_dout;
wire    A_inter_2_3_V_empty_n;
wire    B_inter_3_2_V_full_n;
wire   [31:0] B_inter_3_2_V_dout;
wire    B_inter_3_2_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_load_a13_U0_ap_ready;
wire    ap_sync_load_a13_U0_ap_ready;
reg    ap_sync_reg_load_a14_U0_ap_ready;
wire    ap_sync_load_a14_U0_ap_ready;
reg    ap_sync_reg_load_a15_U0_ap_ready;
wire    ap_sync_load_a15_U0_ap_ready;
reg    ap_sync_reg_load_b16_U0_ap_ready;
wire    ap_sync_load_b16_U0_ap_ready;
reg    ap_sync_reg_load_b17_U0_ap_ready;
wire    ap_sync_load_b17_U0_ap_ready;
reg    ap_sync_reg_load_b18_U0_ap_ready;
wire    ap_sync_load_b18_U0_ap_ready;
wire   [0:0] start_for_PE19_U0_din;
wire    start_for_PE19_U0_full_n;
wire   [0:0] start_for_PE19_U0_dout;
wire    start_for_PE19_U0_empty_n;
wire   [0:0] start_for_PE22_U0_din;
wire    start_for_PE22_U0_full_n;
wire   [0:0] start_for_PE22_U0_dout;
wire    start_for_PE22_U0_empty_n;
wire   [0:0] start_for_PE25_U0_din;
wire    start_for_PE25_U0_full_n;
wire   [0:0] start_for_PE25_U0_dout;
wire    start_for_PE25_U0_empty_n;
wire    load_b16_U0_start_full_n;
wire    load_b16_U0_start_write;
wire   [0:0] start_for_PE20_U0_din;
wire    start_for_PE20_U0_full_n;
wire   [0:0] start_for_PE20_U0_dout;
wire    start_for_PE20_U0_empty_n;
wire   [0:0] start_for_PE21_U0_din;
wire    start_for_PE21_U0_full_n;
wire   [0:0] start_for_PE21_U0_dout;
wire    start_for_PE21_U0_empty_n;
wire    PE19_U0_start_full_n;
wire    PE19_U0_start_write;
wire   [0:0] start_for_PE23_U0_din;
wire    start_for_PE23_U0_full_n;
wire   [0:0] start_for_PE23_U0_dout;
wire    start_for_PE23_U0_empty_n;
wire   [0:0] start_for_PE24_U0_din;
wire    start_for_PE24_U0_full_n;
wire   [0:0] start_for_PE24_U0_dout;
wire    start_for_PE24_U0_empty_n;
wire   [0:0] start_for_drain_a28_U0_din;
wire    start_for_drain_a28_U0_full_n;
wire   [0:0] start_for_drain_a28_U0_dout;
wire    start_for_drain_a28_U0_empty_n;
wire    PE22_U0_start_full_n;
wire    PE22_U0_start_write;
wire    PE23_U0_start_full_n;
wire    PE23_U0_start_write;
wire   [0:0] start_for_PE27_U0_din;
wire    start_for_PE27_U0_full_n;
wire   [0:0] start_for_PE27_U0_dout;
wire    start_for_PE27_U0_empty_n;
wire   [0:0] start_for_drain_a29_U0_din;
wire    start_for_drain_a29_U0_full_n;
wire   [0:0] start_for_drain_a29_U0_dout;
wire    start_for_drain_a29_U0_empty_n;
wire   [0:0] start_for_PE26_U0_din;
wire    start_for_PE26_U0_full_n;
wire   [0:0] start_for_PE26_U0_dout;
wire    start_for_PE26_U0_empty_n;
wire   [0:0] start_for_drain_b31_U0_din;
wire    start_for_drain_b31_U0_full_n;
wire   [0:0] start_for_drain_b31_U0_dout;
wire    start_for_drain_b31_U0_empty_n;
wire   [0:0] start_for_drain_b32_U0_din;
wire    start_for_drain_b32_U0_full_n;
wire   [0:0] start_for_drain_b32_U0_dout;
wire    start_for_drain_b32_U0_empty_n;
wire   [0:0] start_for_drain_a30_U0_din;
wire    start_for_drain_a30_U0_full_n;
wire   [0:0] start_for_drain_a30_U0_dout;
wire    start_for_drain_a30_U0_empty_n;
wire   [0:0] start_for_drain_b33_U0_din;
wire    start_for_drain_b33_U0_full_n;
wire   [0:0] start_for_drain_b33_U0_dout;
wire    start_for_drain_b33_U0_empty_n;
wire    drain_a28_U0_start_full_n;
wire    drain_a28_U0_start_write;
wire    drain_a29_U0_start_full_n;
wire    drain_a29_U0_start_write;
wire    drain_a30_U0_start_full_n;
wire    drain_a30_U0_start_write;
wire    drain_b31_U0_start_full_n;
wire    drain_b31_U0_start_write;
wire    drain_b32_U0_start_full_n;
wire    drain_b32_U0_start_write;
wire    drain_b33_U0_start_full_n;
wire    drain_b33_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_load_a13_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_a14_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_a15_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_b16_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_b17_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_b18_U0_ap_ready = 1'b0;
end

systolic_array_load_a13 load_a13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_a13_U0_ap_start),
    .start_full_n(start_for_PE19_U0_full_n),
    .ap_done(load_a13_U0_ap_done),
    .ap_continue(load_a13_U0_ap_continue),
    .ap_idle(load_a13_U0_ap_idle),
    .ap_ready(load_a13_U0_ap_ready),
    .start_out(load_a13_U0_start_out),
    .start_write(load_a13_U0_start_write),
    .A_nxt_din(load_a13_U0_A_nxt_din),
    .A_nxt_full_n(A_inter_0_0_V_full_n),
    .A_nxt_write(load_a13_U0_A_nxt_write),
    .A_0_address0(load_a13_U0_A_0_address0),
    .A_0_ce0(load_a13_U0_A_0_ce0),
    .A_0_q0(A_0_q0)
);

systolic_array_load_a14 load_a14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_a14_U0_ap_start),
    .start_full_n(start_for_PE22_U0_full_n),
    .ap_done(load_a14_U0_ap_done),
    .ap_continue(load_a14_U0_ap_continue),
    .ap_idle(load_a14_U0_ap_idle),
    .ap_ready(load_a14_U0_ap_ready),
    .start_out(load_a14_U0_start_out),
    .start_write(load_a14_U0_start_write),
    .A_nxt14_din(load_a14_U0_A_nxt14_din),
    .A_nxt14_full_n(A_inter_1_0_V_full_n),
    .A_nxt14_write(load_a14_U0_A_nxt14_write),
    .A_1_address0(load_a14_U0_A_1_address0),
    .A_1_ce0(load_a14_U0_A_1_ce0),
    .A_1_q0(A_1_q0)
);

systolic_array_load_a15 load_a15_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_a15_U0_ap_start),
    .start_full_n(start_for_PE25_U0_full_n),
    .ap_done(load_a15_U0_ap_done),
    .ap_continue(load_a15_U0_ap_continue),
    .ap_idle(load_a15_U0_ap_idle),
    .ap_ready(load_a15_U0_ap_ready),
    .start_out(load_a15_U0_start_out),
    .start_write(load_a15_U0_start_write),
    .A_nxt28_din(load_a15_U0_A_nxt28_din),
    .A_nxt28_full_n(A_inter_2_0_V_full_n),
    .A_nxt28_write(load_a15_U0_A_nxt28_write),
    .A_2_address0(load_a15_U0_A_2_address0),
    .A_2_ce0(load_a15_U0_A_2_ce0),
    .A_2_q0(A_2_q0)
);

systolic_array_load_b16 load_b16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_b16_U0_ap_start),
    .ap_done(load_b16_U0_ap_done),
    .ap_continue(load_b16_U0_ap_continue),
    .ap_idle(load_b16_U0_ap_idle),
    .ap_ready(load_b16_U0_ap_ready),
    .B_nxt_din(load_b16_U0_B_nxt_din),
    .B_nxt_full_n(B_inter_0_0_V_full_n),
    .B_nxt_write(load_b16_U0_B_nxt_write)
);

systolic_array_load_b17 load_b17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_b17_U0_ap_start),
    .start_full_n(start_for_PE20_U0_full_n),
    .ap_done(load_b17_U0_ap_done),
    .ap_continue(load_b17_U0_ap_continue),
    .ap_idle(load_b17_U0_ap_idle),
    .ap_ready(load_b17_U0_ap_ready),
    .start_out(load_b17_U0_start_out),
    .start_write(load_b17_U0_start_write),
    .B_nxt1_din(load_b17_U0_B_nxt1_din),
    .B_nxt1_full_n(B_inter_0_1_V_full_n),
    .B_nxt1_write(load_b17_U0_B_nxt1_write)
);

systolic_array_load_b18 load_b18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_b18_U0_ap_start),
    .start_full_n(start_for_PE21_U0_full_n),
    .ap_done(load_b18_U0_ap_done),
    .ap_continue(load_b18_U0_ap_continue),
    .ap_idle(load_b18_U0_ap_idle),
    .ap_ready(load_b18_U0_ap_ready),
    .start_out(load_b18_U0_start_out),
    .start_write(load_b18_U0_start_write),
    .B_nxt2_din(load_b18_U0_B_nxt2_din),
    .B_nxt2_full_n(B_inter_0_2_V_full_n),
    .B_nxt2_write(load_b18_U0_B_nxt2_write)
);

systolic_array_PE19 PE19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE19_U0_ap_start),
    .ap_done(PE19_U0_ap_done),
    .ap_continue(PE19_U0_ap_continue),
    .ap_idle(PE19_U0_ap_idle),
    .ap_ready(PE19_U0_ap_ready),
    .A_pre_dout(A_inter_0_0_V_dout),
    .A_pre_empty_n(A_inter_0_0_V_empty_n),
    .A_pre_read(PE19_U0_A_pre_read),
    .B_pre_dout(B_inter_0_0_V_dout),
    .B_pre_empty_n(B_inter_0_0_V_empty_n),
    .B_pre_read(PE19_U0_B_pre_read),
    .A_nxt20_din(PE19_U0_A_nxt20_din),
    .A_nxt20_full_n(A_inter_0_1_V_full_n),
    .A_nxt20_write(PE19_U0_A_nxt20_write),
    .B_nxt8_din(PE19_U0_B_nxt8_din),
    .B_nxt8_full_n(B_inter_1_0_V_full_n),
    .B_nxt8_write(PE19_U0_B_nxt8_write)
);

systolic_array_PE20 PE20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE20_U0_ap_start),
    .start_full_n(start_for_PE23_U0_full_n),
    .ap_done(PE20_U0_ap_done),
    .ap_continue(PE20_U0_ap_continue),
    .ap_idle(PE20_U0_ap_idle),
    .ap_ready(PE20_U0_ap_ready),
    .start_out(PE20_U0_start_out),
    .start_write(PE20_U0_start_write),
    .A_pre1_dout(A_inter_0_1_V_dout),
    .A_pre1_empty_n(A_inter_0_1_V_empty_n),
    .A_pre1_read(PE20_U0_A_pre1_read),
    .B_pre12_dout(B_inter_0_1_V_dout),
    .B_pre12_empty_n(B_inter_0_1_V_empty_n),
    .B_pre12_read(PE20_U0_B_pre12_read),
    .A_nxt21_din(PE20_U0_A_nxt21_din),
    .A_nxt21_full_n(A_inter_0_2_V_full_n),
    .A_nxt21_write(PE20_U0_A_nxt21_write),
    .B_nxt831_din(PE20_U0_B_nxt831_din),
    .B_nxt831_full_n(B_inter_1_1_V_full_n),
    .B_nxt831_write(PE20_U0_B_nxt831_write)
);

systolic_array_PE21 PE21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE21_U0_ap_start),
    .start_full_n(PE21_U0_start_full_n),
    .ap_done(PE21_U0_ap_done),
    .ap_continue(PE21_U0_ap_continue),
    .ap_idle(PE21_U0_ap_idle),
    .ap_ready(PE21_U0_ap_ready),
    .start_out(PE21_U0_start_out),
    .start_write(PE21_U0_start_write),
    .A_pre2_dout(A_inter_0_2_V_dout),
    .A_pre2_empty_n(A_inter_0_2_V_empty_n),
    .A_pre2_read(PE21_U0_A_pre2_read),
    .B_pre13_dout(B_inter_0_2_V_dout),
    .B_pre13_empty_n(B_inter_0_2_V_empty_n),
    .B_pre13_read(PE21_U0_B_pre13_read),
    .A_nxt22_din(PE21_U0_A_nxt22_din),
    .A_nxt22_full_n(A_inter_0_3_V_full_n),
    .A_nxt22_write(PE21_U0_A_nxt22_write),
    .B_nxt832_din(PE21_U0_B_nxt832_din),
    .B_nxt832_full_n(B_inter_1_2_V_full_n),
    .B_nxt832_write(PE21_U0_B_nxt832_write)
);

systolic_array_PE22 PE22_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE22_U0_ap_start),
    .ap_done(PE22_U0_ap_done),
    .ap_continue(PE22_U0_ap_continue),
    .ap_idle(PE22_U0_ap_idle),
    .ap_ready(PE22_U0_ap_ready),
    .A_pre14_dout(A_inter_1_0_V_dout),
    .A_pre14_empty_n(A_inter_1_0_V_empty_n),
    .A_pre14_read(PE22_U0_A_pre14_read),
    .B_pre3_dout(B_inter_1_0_V_dout),
    .B_pre3_empty_n(B_inter_1_0_V_empty_n),
    .B_pre3_read(PE22_U0_B_pre3_read),
    .A_nxt623_din(PE22_U0_A_nxt623_din),
    .A_nxt623_full_n(A_inter_1_1_V_full_n),
    .A_nxt623_write(PE22_U0_A_nxt623_write),
    .B_nxt9_din(PE22_U0_B_nxt9_din),
    .B_nxt9_full_n(B_inter_2_0_V_full_n),
    .B_nxt9_write(PE22_U0_B_nxt9_write)
);

systolic_array_PE23 PE23_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE23_U0_ap_start),
    .ap_done(PE23_U0_ap_done),
    .ap_continue(PE23_U0_ap_continue),
    .ap_idle(PE23_U0_ap_idle),
    .ap_ready(PE23_U0_ap_ready),
    .A_pre15_dout(A_inter_1_1_V_dout),
    .A_pre15_empty_n(A_inter_1_1_V_empty_n),
    .A_pre15_read(PE23_U0_A_pre15_read),
    .B_pre314_dout(B_inter_1_1_V_dout),
    .B_pre314_empty_n(B_inter_1_1_V_empty_n),
    .B_pre314_read(PE23_U0_B_pre314_read),
    .A_nxt624_din(PE23_U0_A_nxt624_din),
    .A_nxt624_full_n(A_inter_1_2_V_full_n),
    .A_nxt624_write(PE23_U0_A_nxt624_write),
    .B_nxt933_din(PE23_U0_B_nxt933_din),
    .B_nxt933_full_n(B_inter_2_1_V_full_n),
    .B_nxt933_write(PE23_U0_B_nxt933_write)
);

systolic_array_PE24 PE24_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE24_U0_ap_start),
    .start_full_n(PE24_U0_start_full_n),
    .ap_done(PE24_U0_ap_done),
    .ap_continue(PE24_U0_ap_continue),
    .ap_idle(PE24_U0_ap_idle),
    .ap_ready(PE24_U0_ap_ready),
    .start_out(PE24_U0_start_out),
    .start_write(PE24_U0_start_write),
    .A_pre16_dout(A_inter_1_2_V_dout),
    .A_pre16_empty_n(A_inter_1_2_V_empty_n),
    .A_pre16_read(PE24_U0_A_pre16_read),
    .B_pre315_dout(B_inter_1_2_V_dout),
    .B_pre315_empty_n(B_inter_1_2_V_empty_n),
    .B_pre315_read(PE24_U0_B_pre315_read),
    .A_nxt625_din(PE24_U0_A_nxt625_din),
    .A_nxt625_full_n(A_inter_1_3_V_full_n),
    .A_nxt625_write(PE24_U0_A_nxt625_write),
    .B_nxt934_din(PE24_U0_B_nxt934_din),
    .B_nxt934_full_n(B_inter_2_2_V_full_n),
    .B_nxt934_write(PE24_U0_B_nxt934_write)
);

systolic_array_PE25 PE25_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE25_U0_ap_start),
    .start_full_n(PE25_U0_start_full_n),
    .ap_done(PE25_U0_ap_done),
    .ap_continue(PE25_U0_ap_continue),
    .ap_idle(PE25_U0_ap_idle),
    .ap_ready(PE25_U0_ap_ready),
    .start_out(PE25_U0_start_out),
    .start_write(PE25_U0_start_write),
    .A_pre28_dout(A_inter_2_0_V_dout),
    .A_pre28_empty_n(A_inter_2_0_V_empty_n),
    .A_pre28_read(PE25_U0_A_pre28_read),
    .B_pre4_dout(B_inter_2_0_V_dout),
    .B_pre4_empty_n(B_inter_2_0_V_empty_n),
    .B_pre4_read(PE25_U0_B_pre4_read),
    .A_nxt726_din(PE25_U0_A_nxt726_din),
    .A_nxt726_full_n(A_inter_2_1_V_full_n),
    .A_nxt726_write(PE25_U0_A_nxt726_write),
    .B_nxt10_din(PE25_U0_B_nxt10_din),
    .B_nxt10_full_n(B_inter_3_0_V_full_n),
    .B_nxt10_write(PE25_U0_B_nxt10_write)
);

systolic_array_PE26 PE26_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE26_U0_ap_start),
    .start_full_n(start_for_drain_b32_U0_full_n),
    .ap_done(PE26_U0_ap_done),
    .ap_continue(PE26_U0_ap_continue),
    .ap_idle(PE26_U0_ap_idle),
    .ap_ready(PE26_U0_ap_ready),
    .start_out(PE26_U0_start_out),
    .start_write(PE26_U0_start_write),
    .A_pre29_dout(A_inter_2_1_V_dout),
    .A_pre29_empty_n(A_inter_2_1_V_empty_n),
    .A_pre29_read(PE26_U0_A_pre29_read),
    .B_pre416_dout(B_inter_2_1_V_dout),
    .B_pre416_empty_n(B_inter_2_1_V_empty_n),
    .B_pre416_read(PE26_U0_B_pre416_read),
    .A_nxt727_din(PE26_U0_A_nxt727_din),
    .A_nxt727_full_n(A_inter_2_2_V_full_n),
    .A_nxt727_write(PE26_U0_A_nxt727_write),
    .B_nxt1035_din(PE26_U0_B_nxt1035_din),
    .B_nxt1035_full_n(B_inter_3_1_V_full_n),
    .B_nxt1035_write(PE26_U0_B_nxt1035_write)
);

systolic_array_PE27 PE27_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(PE27_U0_ap_start),
    .start_full_n(PE27_U0_start_full_n),
    .ap_done(PE27_U0_ap_done),
    .ap_continue(PE27_U0_ap_continue),
    .ap_idle(PE27_U0_ap_idle),
    .ap_ready(PE27_U0_ap_ready),
    .start_out(PE27_U0_start_out),
    .start_write(PE27_U0_start_write),
    .A_pre210_dout(A_inter_2_2_V_dout),
    .A_pre210_empty_n(A_inter_2_2_V_empty_n),
    .A_pre210_read(PE27_U0_A_pre210_read),
    .B_pre417_dout(B_inter_2_2_V_dout),
    .B_pre417_empty_n(B_inter_2_2_V_empty_n),
    .B_pre417_read(PE27_U0_B_pre417_read),
    .A_nxt728_din(PE27_U0_A_nxt728_din),
    .A_nxt728_full_n(A_inter_2_3_V_full_n),
    .A_nxt728_write(PE27_U0_A_nxt728_write),
    .B_nxt1036_din(PE27_U0_B_nxt1036_din),
    .B_nxt1036_full_n(B_inter_3_2_V_full_n),
    .B_nxt1036_write(PE27_U0_B_nxt1036_write)
);

systolic_array_drain_a28 drain_a28_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_a28_U0_ap_start),
    .ap_done(drain_a28_U0_ap_done),
    .ap_continue(drain_a28_U0_ap_continue),
    .ap_idle(drain_a28_U0_ap_idle),
    .ap_ready(drain_a28_U0_ap_ready),
    .A_pre_V3_dout(A_inter_0_3_V_dout),
    .A_pre_V3_empty_n(A_inter_0_3_V_empty_n),
    .A_pre_V3_read(drain_a28_U0_A_pre_V3_read)
);

systolic_array_drain_a29 drain_a29_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_a29_U0_ap_start),
    .ap_done(drain_a29_U0_ap_done),
    .ap_continue(drain_a29_U0_ap_continue),
    .ap_idle(drain_a29_U0_ap_idle),
    .ap_ready(drain_a29_U0_ap_ready),
    .A_pre_V17_dout(A_inter_1_3_V_dout),
    .A_pre_V17_empty_n(A_inter_1_3_V_empty_n),
    .A_pre_V17_read(drain_a29_U0_A_pre_V17_read)
);

systolic_array_drain_a30 drain_a30_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_a30_U0_ap_start),
    .ap_done(drain_a30_U0_ap_done),
    .ap_continue(drain_a30_U0_ap_continue),
    .ap_idle(drain_a30_U0_ap_idle),
    .ap_ready(drain_a30_U0_ap_ready),
    .A_pre_V211_dout(A_inter_2_3_V_dout),
    .A_pre_V211_empty_n(A_inter_2_3_V_empty_n),
    .A_pre_V211_read(drain_a30_U0_A_pre_V211_read)
);

systolic_array_drain_b31 drain_b31_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_b31_U0_ap_start),
    .ap_done(drain_b31_U0_ap_done),
    .ap_continue(drain_b31_U0_ap_continue),
    .ap_idle(drain_b31_U0_ap_idle),
    .ap_ready(drain_b31_U0_ap_ready),
    .B_pre_V3_dout(B_inter_3_0_V_dout),
    .B_pre_V3_empty_n(B_inter_3_0_V_empty_n),
    .B_pre_V3_read(drain_b31_U0_B_pre_V3_read)
);

systolic_array_drain_b32 drain_b32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_b32_U0_ap_start),
    .ap_done(drain_b32_U0_ap_done),
    .ap_continue(drain_b32_U0_ap_continue),
    .ap_idle(drain_b32_U0_ap_idle),
    .ap_ready(drain_b32_U0_ap_ready),
    .B_pre_V39_dout(B_inter_3_1_V_dout),
    .B_pre_V39_empty_n(B_inter_3_1_V_empty_n),
    .B_pre_V39_read(drain_b32_U0_B_pre_V39_read)
);

systolic_array_drain_b33 drain_b33_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(drain_b33_U0_ap_start),
    .ap_done(drain_b33_U0_ap_done),
    .ap_continue(drain_b33_U0_ap_continue),
    .ap_idle(drain_b33_U0_ap_idle),
    .ap_ready(drain_b33_U0_ap_ready),
    .B_pre_V310_dout(B_inter_3_2_V_dout),
    .B_pre_V310_empty_n(B_inter_3_2_V_empty_n),
    .B_pre_V310_read(drain_b33_U0_B_pre_V310_read)
);

systolic_array_fifo_w32_d2_S A_inter_0_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_a13_U0_A_nxt_din),
    .if_full_n(A_inter_0_0_V_full_n),
    .if_write(load_a13_U0_A_nxt_write),
    .if_dout(A_inter_0_0_V_dout),
    .if_empty_n(A_inter_0_0_V_empty_n),
    .if_read(PE19_U0_A_pre_read)
);

systolic_array_fifo_w32_d2_S A_inter_1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_a14_U0_A_nxt14_din),
    .if_full_n(A_inter_1_0_V_full_n),
    .if_write(load_a14_U0_A_nxt14_write),
    .if_dout(A_inter_1_0_V_dout),
    .if_empty_n(A_inter_1_0_V_empty_n),
    .if_read(PE22_U0_A_pre14_read)
);

systolic_array_fifo_w32_d2_S A_inter_2_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_a15_U0_A_nxt28_din),
    .if_full_n(A_inter_2_0_V_full_n),
    .if_write(load_a15_U0_A_nxt28_write),
    .if_dout(A_inter_2_0_V_dout),
    .if_empty_n(A_inter_2_0_V_empty_n),
    .if_read(PE25_U0_A_pre28_read)
);

systolic_array_fifo_w32_d2_S B_inter_0_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_b16_U0_B_nxt_din),
    .if_full_n(B_inter_0_0_V_full_n),
    .if_write(load_b16_U0_B_nxt_write),
    .if_dout(B_inter_0_0_V_dout),
    .if_empty_n(B_inter_0_0_V_empty_n),
    .if_read(PE19_U0_B_pre_read)
);

systolic_array_fifo_w32_d2_S B_inter_0_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_b17_U0_B_nxt1_din),
    .if_full_n(B_inter_0_1_V_full_n),
    .if_write(load_b17_U0_B_nxt1_write),
    .if_dout(B_inter_0_1_V_dout),
    .if_empty_n(B_inter_0_1_V_empty_n),
    .if_read(PE20_U0_B_pre12_read)
);

systolic_array_fifo_w32_d2_S B_inter_0_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_b18_U0_B_nxt2_din),
    .if_full_n(B_inter_0_2_V_full_n),
    .if_write(load_b18_U0_B_nxt2_write),
    .if_dout(B_inter_0_2_V_dout),
    .if_empty_n(B_inter_0_2_V_empty_n),
    .if_read(PE21_U0_B_pre13_read)
);

systolic_array_fifo_w32_d2_S A_inter_0_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE19_U0_A_nxt20_din),
    .if_full_n(A_inter_0_1_V_full_n),
    .if_write(PE19_U0_A_nxt20_write),
    .if_dout(A_inter_0_1_V_dout),
    .if_empty_n(A_inter_0_1_V_empty_n),
    .if_read(PE20_U0_A_pre1_read)
);

systolic_array_fifo_w32_d2_S B_inter_1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE19_U0_B_nxt8_din),
    .if_full_n(B_inter_1_0_V_full_n),
    .if_write(PE19_U0_B_nxt8_write),
    .if_dout(B_inter_1_0_V_dout),
    .if_empty_n(B_inter_1_0_V_empty_n),
    .if_read(PE22_U0_B_pre3_read)
);

systolic_array_fifo_w32_d2_S A_inter_0_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE20_U0_A_nxt21_din),
    .if_full_n(A_inter_0_2_V_full_n),
    .if_write(PE20_U0_A_nxt21_write),
    .if_dout(A_inter_0_2_V_dout),
    .if_empty_n(A_inter_0_2_V_empty_n),
    .if_read(PE21_U0_A_pre2_read)
);

systolic_array_fifo_w32_d2_S B_inter_1_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE20_U0_B_nxt831_din),
    .if_full_n(B_inter_1_1_V_full_n),
    .if_write(PE20_U0_B_nxt831_write),
    .if_dout(B_inter_1_1_V_dout),
    .if_empty_n(B_inter_1_1_V_empty_n),
    .if_read(PE23_U0_B_pre314_read)
);

systolic_array_fifo_w32_d2_S A_inter_0_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE21_U0_A_nxt22_din),
    .if_full_n(A_inter_0_3_V_full_n),
    .if_write(PE21_U0_A_nxt22_write),
    .if_dout(A_inter_0_3_V_dout),
    .if_empty_n(A_inter_0_3_V_empty_n),
    .if_read(drain_a28_U0_A_pre_V3_read)
);

systolic_array_fifo_w32_d2_S B_inter_1_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE21_U0_B_nxt832_din),
    .if_full_n(B_inter_1_2_V_full_n),
    .if_write(PE21_U0_B_nxt832_write),
    .if_dout(B_inter_1_2_V_dout),
    .if_empty_n(B_inter_1_2_V_empty_n),
    .if_read(PE24_U0_B_pre315_read)
);

systolic_array_fifo_w32_d2_S A_inter_1_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE22_U0_A_nxt623_din),
    .if_full_n(A_inter_1_1_V_full_n),
    .if_write(PE22_U0_A_nxt623_write),
    .if_dout(A_inter_1_1_V_dout),
    .if_empty_n(A_inter_1_1_V_empty_n),
    .if_read(PE23_U0_A_pre15_read)
);

systolic_array_fifo_w32_d2_S B_inter_2_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE22_U0_B_nxt9_din),
    .if_full_n(B_inter_2_0_V_full_n),
    .if_write(PE22_U0_B_nxt9_write),
    .if_dout(B_inter_2_0_V_dout),
    .if_empty_n(B_inter_2_0_V_empty_n),
    .if_read(PE25_U0_B_pre4_read)
);

systolic_array_fifo_w32_d2_S A_inter_1_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE23_U0_A_nxt624_din),
    .if_full_n(A_inter_1_2_V_full_n),
    .if_write(PE23_U0_A_nxt624_write),
    .if_dout(A_inter_1_2_V_dout),
    .if_empty_n(A_inter_1_2_V_empty_n),
    .if_read(PE24_U0_A_pre16_read)
);

systolic_array_fifo_w32_d2_S B_inter_2_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE23_U0_B_nxt933_din),
    .if_full_n(B_inter_2_1_V_full_n),
    .if_write(PE23_U0_B_nxt933_write),
    .if_dout(B_inter_2_1_V_dout),
    .if_empty_n(B_inter_2_1_V_empty_n),
    .if_read(PE26_U0_B_pre416_read)
);

systolic_array_fifo_w32_d2_S A_inter_1_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE24_U0_A_nxt625_din),
    .if_full_n(A_inter_1_3_V_full_n),
    .if_write(PE24_U0_A_nxt625_write),
    .if_dout(A_inter_1_3_V_dout),
    .if_empty_n(A_inter_1_3_V_empty_n),
    .if_read(drain_a29_U0_A_pre_V17_read)
);

systolic_array_fifo_w32_d2_S B_inter_2_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE24_U0_B_nxt934_din),
    .if_full_n(B_inter_2_2_V_full_n),
    .if_write(PE24_U0_B_nxt934_write),
    .if_dout(B_inter_2_2_V_dout),
    .if_empty_n(B_inter_2_2_V_empty_n),
    .if_read(PE27_U0_B_pre417_read)
);

systolic_array_fifo_w32_d2_S A_inter_2_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE25_U0_A_nxt726_din),
    .if_full_n(A_inter_2_1_V_full_n),
    .if_write(PE25_U0_A_nxt726_write),
    .if_dout(A_inter_2_1_V_dout),
    .if_empty_n(A_inter_2_1_V_empty_n),
    .if_read(PE26_U0_A_pre29_read)
);

systolic_array_fifo_w32_d2_S B_inter_3_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE25_U0_B_nxt10_din),
    .if_full_n(B_inter_3_0_V_full_n),
    .if_write(PE25_U0_B_nxt10_write),
    .if_dout(B_inter_3_0_V_dout),
    .if_empty_n(B_inter_3_0_V_empty_n),
    .if_read(drain_b31_U0_B_pre_V3_read)
);

systolic_array_fifo_w32_d2_S A_inter_2_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE26_U0_A_nxt727_din),
    .if_full_n(A_inter_2_2_V_full_n),
    .if_write(PE26_U0_A_nxt727_write),
    .if_dout(A_inter_2_2_V_dout),
    .if_empty_n(A_inter_2_2_V_empty_n),
    .if_read(PE27_U0_A_pre210_read)
);

systolic_array_fifo_w32_d2_S B_inter_3_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE26_U0_B_nxt1035_din),
    .if_full_n(B_inter_3_1_V_full_n),
    .if_write(PE26_U0_B_nxt1035_write),
    .if_dout(B_inter_3_1_V_dout),
    .if_empty_n(B_inter_3_1_V_empty_n),
    .if_read(drain_b32_U0_B_pre_V39_read)
);

systolic_array_fifo_w32_d2_S A_inter_2_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE27_U0_A_nxt728_din),
    .if_full_n(A_inter_2_3_V_full_n),
    .if_write(PE27_U0_A_nxt728_write),
    .if_dout(A_inter_2_3_V_dout),
    .if_empty_n(A_inter_2_3_V_empty_n),
    .if_read(drain_a30_U0_A_pre_V211_read)
);

systolic_array_fifo_w32_d2_S B_inter_3_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(PE27_U0_B_nxt1036_din),
    .if_full_n(B_inter_3_2_V_full_n),
    .if_write(PE27_U0_B_nxt1036_write),
    .if_dout(B_inter_3_2_V_dout),
    .if_empty_n(B_inter_3_2_V_empty_n),
    .if_read(drain_b33_U0_B_pre_V310_read)
);

systolic_array_start_for_PE19_U0 start_for_PE19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE19_U0_din),
    .if_full_n(start_for_PE19_U0_full_n),
    .if_write(load_a13_U0_start_write),
    .if_dout(start_for_PE19_U0_dout),
    .if_empty_n(start_for_PE19_U0_empty_n),
    .if_read(PE19_U0_ap_ready)
);

systolic_array_start_for_PE22_U0 start_for_PE22_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE22_U0_din),
    .if_full_n(start_for_PE22_U0_full_n),
    .if_write(load_a14_U0_start_write),
    .if_dout(start_for_PE22_U0_dout),
    .if_empty_n(start_for_PE22_U0_empty_n),
    .if_read(PE22_U0_ap_ready)
);

systolic_array_start_for_PE25_U0 start_for_PE25_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE25_U0_din),
    .if_full_n(start_for_PE25_U0_full_n),
    .if_write(load_a15_U0_start_write),
    .if_dout(start_for_PE25_U0_dout),
    .if_empty_n(start_for_PE25_U0_empty_n),
    .if_read(PE25_U0_ap_ready)
);

systolic_array_start_for_PE20_U0 start_for_PE20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE20_U0_din),
    .if_full_n(start_for_PE20_U0_full_n),
    .if_write(load_b17_U0_start_write),
    .if_dout(start_for_PE20_U0_dout),
    .if_empty_n(start_for_PE20_U0_empty_n),
    .if_read(PE20_U0_ap_ready)
);

systolic_array_start_for_PE21_U0 start_for_PE21_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE21_U0_din),
    .if_full_n(start_for_PE21_U0_full_n),
    .if_write(load_b18_U0_start_write),
    .if_dout(start_for_PE21_U0_dout),
    .if_empty_n(start_for_PE21_U0_empty_n),
    .if_read(PE21_U0_ap_ready)
);

systolic_array_start_for_PE23_U0 start_for_PE23_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE23_U0_din),
    .if_full_n(start_for_PE23_U0_full_n),
    .if_write(PE20_U0_start_write),
    .if_dout(start_for_PE23_U0_dout),
    .if_empty_n(start_for_PE23_U0_empty_n),
    .if_read(PE23_U0_ap_ready)
);

systolic_array_start_for_PE24_U0 start_for_PE24_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE24_U0_din),
    .if_full_n(start_for_PE24_U0_full_n),
    .if_write(PE21_U0_start_write),
    .if_dout(start_for_PE24_U0_dout),
    .if_empty_n(start_for_PE24_U0_empty_n),
    .if_read(PE24_U0_ap_ready)
);

systolic_array_start_for_drain_a28_U0 start_for_drain_a28_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_a28_U0_din),
    .if_full_n(start_for_drain_a28_U0_full_n),
    .if_write(PE21_U0_start_write),
    .if_dout(start_for_drain_a28_U0_dout),
    .if_empty_n(start_for_drain_a28_U0_empty_n),
    .if_read(drain_a28_U0_ap_ready)
);

systolic_array_start_for_PE27_U0 start_for_PE27_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE27_U0_din),
    .if_full_n(start_for_PE27_U0_full_n),
    .if_write(PE24_U0_start_write),
    .if_dout(start_for_PE27_U0_dout),
    .if_empty_n(start_for_PE27_U0_empty_n),
    .if_read(PE27_U0_ap_ready)
);

systolic_array_start_for_drain_a29_U0 start_for_drain_a29_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_a29_U0_din),
    .if_full_n(start_for_drain_a29_U0_full_n),
    .if_write(PE24_U0_start_write),
    .if_dout(start_for_drain_a29_U0_dout),
    .if_empty_n(start_for_drain_a29_U0_empty_n),
    .if_read(drain_a29_U0_ap_ready)
);

systolic_array_start_for_PE26_U0 start_for_PE26_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_PE26_U0_din),
    .if_full_n(start_for_PE26_U0_full_n),
    .if_write(PE25_U0_start_write),
    .if_dout(start_for_PE26_U0_dout),
    .if_empty_n(start_for_PE26_U0_empty_n),
    .if_read(PE26_U0_ap_ready)
);

systolic_array_start_for_drain_b31_U0 start_for_drain_b31_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_b31_U0_din),
    .if_full_n(start_for_drain_b31_U0_full_n),
    .if_write(PE25_U0_start_write),
    .if_dout(start_for_drain_b31_U0_dout),
    .if_empty_n(start_for_drain_b31_U0_empty_n),
    .if_read(drain_b31_U0_ap_ready)
);

systolic_array_start_for_drain_b32_U0 start_for_drain_b32_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_b32_U0_din),
    .if_full_n(start_for_drain_b32_U0_full_n),
    .if_write(PE26_U0_start_write),
    .if_dout(start_for_drain_b32_U0_dout),
    .if_empty_n(start_for_drain_b32_U0_empty_n),
    .if_read(drain_b32_U0_ap_ready)
);

systolic_array_start_for_drain_a30_U0 start_for_drain_a30_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_a30_U0_din),
    .if_full_n(start_for_drain_a30_U0_full_n),
    .if_write(PE27_U0_start_write),
    .if_dout(start_for_drain_a30_U0_dout),
    .if_empty_n(start_for_drain_a30_U0_empty_n),
    .if_read(drain_a30_U0_ap_ready)
);

systolic_array_start_for_drain_b33_U0 start_for_drain_b33_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_drain_b33_U0_din),
    .if_full_n(start_for_drain_b33_U0_full_n),
    .if_write(PE27_U0_start_write),
    .if_dout(start_for_drain_b33_U0_dout),
    .if_empty_n(start_for_drain_b33_U0_empty_n),
    .if_read(drain_b33_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_a13_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_a13_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_a13_U0_ap_ready <= ap_sync_load_a13_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_a14_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_a14_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_a14_U0_ap_ready <= ap_sync_load_a14_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_a15_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_a15_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_a15_U0_ap_ready <= ap_sync_load_a15_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_b16_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_b16_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_b16_U0_ap_ready <= ap_sync_load_b16_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_b17_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_b17_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_b17_U0_ap_ready <= ap_sync_load_b17_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_b18_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_b18_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_b18_U0_ap_ready <= ap_sync_load_b18_U0_ap_ready;
        end
    end
end

assign A_0_address0 = load_a13_U0_A_0_address0;

assign A_0_address1 = 2'd0;

assign A_0_ce0 = load_a13_U0_A_0_ce0;

assign A_0_ce1 = 1'b0;

assign A_0_d0 = 32'd0;

assign A_0_d1 = 32'd0;

assign A_0_we0 = 1'b0;

assign A_0_we1 = 1'b0;

assign A_1_address0 = load_a14_U0_A_1_address0;

assign A_1_address1 = 2'd0;

assign A_1_ce0 = load_a14_U0_A_1_ce0;

assign A_1_ce1 = 1'b0;

assign A_1_d0 = 32'd0;

assign A_1_d1 = 32'd0;

assign A_1_we0 = 1'b0;

assign A_1_we1 = 1'b0;

assign A_2_address0 = load_a15_U0_A_2_address0;

assign A_2_address1 = 2'd0;

assign A_2_ce0 = load_a15_U0_A_2_ce0;

assign A_2_ce1 = 1'b0;

assign A_2_d0 = 32'd0;

assign A_2_d1 = 32'd0;

assign A_2_we0 = 1'b0;

assign A_2_we1 = 1'b0;

assign PE19_U0_ap_continue = 1'b1;

assign PE19_U0_ap_start = start_for_PE19_U0_empty_n;

assign PE19_U0_start_full_n = 1'b1;

assign PE19_U0_start_write = 1'b0;

assign PE20_U0_ap_continue = 1'b1;

assign PE20_U0_ap_start = start_for_PE20_U0_empty_n;

assign PE21_U0_ap_continue = 1'b1;

assign PE21_U0_ap_start = start_for_PE21_U0_empty_n;

assign PE21_U0_start_full_n = (start_for_drain_a28_U0_full_n & start_for_PE24_U0_full_n);

assign PE22_U0_ap_continue = 1'b1;

assign PE22_U0_ap_start = start_for_PE22_U0_empty_n;

assign PE22_U0_start_full_n = 1'b1;

assign PE22_U0_start_write = 1'b0;

assign PE23_U0_ap_continue = 1'b1;

assign PE23_U0_ap_start = start_for_PE23_U0_empty_n;

assign PE23_U0_start_full_n = 1'b1;

assign PE23_U0_start_write = 1'b0;

assign PE24_U0_ap_continue = 1'b1;

assign PE24_U0_ap_start = start_for_PE24_U0_empty_n;

assign PE24_U0_start_full_n = (start_for_drain_a29_U0_full_n & start_for_PE27_U0_full_n);

assign PE25_U0_ap_continue = 1'b1;

assign PE25_U0_ap_start = start_for_PE25_U0_empty_n;

assign PE25_U0_start_full_n = (start_for_drain_b31_U0_full_n & start_for_PE26_U0_full_n);

assign PE26_U0_ap_continue = 1'b1;

assign PE26_U0_ap_start = start_for_PE26_U0_empty_n;

assign PE27_U0_ap_continue = 1'b1;

assign PE27_U0_ap_start = start_for_PE27_U0_empty_n;

assign PE27_U0_start_full_n = (start_for_drain_b33_U0_full_n & start_for_drain_a30_U0_full_n);

assign ap_done = ap_sync_done;

assign ap_idle = (load_b18_U0_ap_idle & load_b17_U0_ap_idle & load_b16_U0_ap_idle & load_a15_U0_ap_idle & load_a14_U0_ap_idle & load_a13_U0_ap_idle & drain_b33_U0_ap_idle & drain_b32_U0_ap_idle & drain_b31_U0_ap_idle & drain_a30_U0_ap_idle & drain_a29_U0_ap_idle & drain_a28_U0_ap_idle & PE27_U0_ap_idle & PE26_U0_ap_idle & PE25_U0_ap_idle & PE24_U0_ap_idle & PE23_U0_ap_idle & PE22_U0_ap_idle & PE21_U0_ap_idle & PE20_U0_ap_idle & PE19_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (drain_b33_U0_ap_done & drain_b32_U0_ap_done & drain_b31_U0_ap_done & drain_a30_U0_ap_done & drain_a29_U0_ap_done & drain_a28_U0_ap_done);

assign ap_sync_load_a13_U0_ap_ready = (load_a13_U0_ap_ready | ap_sync_reg_load_a13_U0_ap_ready);

assign ap_sync_load_a14_U0_ap_ready = (load_a14_U0_ap_ready | ap_sync_reg_load_a14_U0_ap_ready);

assign ap_sync_load_a15_U0_ap_ready = (load_a15_U0_ap_ready | ap_sync_reg_load_a15_U0_ap_ready);

assign ap_sync_load_b16_U0_ap_ready = (load_b16_U0_ap_ready | ap_sync_reg_load_b16_U0_ap_ready);

assign ap_sync_load_b17_U0_ap_ready = (load_b17_U0_ap_ready | ap_sync_reg_load_b17_U0_ap_ready);

assign ap_sync_load_b18_U0_ap_ready = (load_b18_U0_ap_ready | ap_sync_reg_load_b18_U0_ap_ready);

assign ap_sync_ready = (ap_sync_load_b18_U0_ap_ready & ap_sync_load_b17_U0_ap_ready & ap_sync_load_b16_U0_ap_ready & ap_sync_load_a15_U0_ap_ready & ap_sync_load_a14_U0_ap_ready & ap_sync_load_a13_U0_ap_ready);

assign drain_a28_U0_ap_continue = ap_sync_continue;

assign drain_a28_U0_ap_start = start_for_drain_a28_U0_empty_n;

assign drain_a28_U0_start_full_n = 1'b1;

assign drain_a28_U0_start_write = 1'b0;

assign drain_a29_U0_ap_continue = ap_sync_continue;

assign drain_a29_U0_ap_start = start_for_drain_a29_U0_empty_n;

assign drain_a29_U0_start_full_n = 1'b1;

assign drain_a29_U0_start_write = 1'b0;

assign drain_a30_U0_ap_continue = ap_sync_continue;

assign drain_a30_U0_ap_start = start_for_drain_a30_U0_empty_n;

assign drain_a30_U0_start_full_n = 1'b1;

assign drain_a30_U0_start_write = 1'b0;

assign drain_b31_U0_ap_continue = ap_sync_continue;

assign drain_b31_U0_ap_start = start_for_drain_b31_U0_empty_n;

assign drain_b31_U0_start_full_n = 1'b1;

assign drain_b31_U0_start_write = 1'b0;

assign drain_b32_U0_ap_continue = ap_sync_continue;

assign drain_b32_U0_ap_start = start_for_drain_b32_U0_empty_n;

assign drain_b32_U0_start_full_n = 1'b1;

assign drain_b32_U0_start_write = 1'b0;

assign drain_b33_U0_ap_continue = ap_sync_continue;

assign drain_b33_U0_ap_start = start_for_drain_b33_U0_empty_n;

assign drain_b33_U0_start_full_n = 1'b1;

assign drain_b33_U0_start_write = 1'b0;

assign load_a13_U0_ap_continue = 1'b1;

assign load_a13_U0_ap_start = ((ap_sync_reg_load_a13_U0_ap_ready ^ 1'b1) & ap_start);

assign load_a14_U0_ap_continue = 1'b1;

assign load_a14_U0_ap_start = ((ap_sync_reg_load_a14_U0_ap_ready ^ 1'b1) & ap_start);

assign load_a15_U0_ap_continue = 1'b1;

assign load_a15_U0_ap_start = ((ap_sync_reg_load_a15_U0_ap_ready ^ 1'b1) & ap_start);

assign load_b16_U0_ap_continue = 1'b1;

assign load_b16_U0_ap_start = ((ap_sync_reg_load_b16_U0_ap_ready ^ 1'b1) & ap_start);

assign load_b16_U0_start_full_n = 1'b1;

assign load_b16_U0_start_write = 1'b0;

assign load_b17_U0_ap_continue = 1'b1;

assign load_b17_U0_ap_start = ((ap_sync_reg_load_b17_U0_ap_ready ^ 1'b1) & ap_start);

assign load_b18_U0_ap_continue = 1'b1;

assign load_b18_U0_ap_start = ((ap_sync_reg_load_b18_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_PE19_U0_din = 1'b1;

assign start_for_PE20_U0_din = 1'b1;

assign start_for_PE21_U0_din = 1'b1;

assign start_for_PE22_U0_din = 1'b1;

assign start_for_PE23_U0_din = 1'b1;

assign start_for_PE24_U0_din = 1'b1;

assign start_for_PE25_U0_din = 1'b1;

assign start_for_PE26_U0_din = 1'b1;

assign start_for_PE27_U0_din = 1'b1;

assign start_for_drain_a28_U0_din = 1'b1;

assign start_for_drain_a29_U0_din = 1'b1;

assign start_for_drain_a30_U0_din = 1'b1;

assign start_for_drain_b31_U0_din = 1'b1;

assign start_for_drain_b32_U0_din = 1'b1;

assign start_for_drain_b33_U0_din = 1'b1;

endmodule //systolic_array_pe_array
