# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/0320xdc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_1} -quiet] -quiet

# XDC: /home/yobuwen/hello-one/ultra96/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
