
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvector_add.h"

/*
* The configuration table for devices
*/

XVector_add_Config XVector_add_ConfigTable[XPAR_XVECTOR_ADD_NUM_INSTANCES] =
{
	{
		XPAR_VECTOR_ADD_0_DEVICE_ID,
		XPAR_VECTOR_ADD_0_S_AXI_CONTROL_BASEADDR
	}
};


